"""
Core type definitions shared across all agent-trust modules.
"""

from __future__ import annotations

import hashlib
import time
import uuid
from dataclasses import dataclass, field
from enum import Enum, IntEnum
from typing import Any, Optional


class TrustLevel(IntEnum):
    """Graduated trust levels for agent interactions."""
    UNTRUSTED = 0
    PROVISIONAL = 1
    BASIC = 2
    VERIFIED = 3
    TRUSTED = 4
    FULLY_TRUSTED = 5


class AlertSeverity(Enum):
    """Severity levels for trust alerts."""
    INFO = "info"
    WARNING = "warning"
    CRITICAL = "critical"
    EMERGENCY = "emergency"


class ComplianceStandard(Enum):
    """Supported compliance standards."""
    GDPR = "gdpr"
    PSD2 = "psd2"
    SOC2 = "soc2"
    HIPAA = "hipaa"
    ISO27001 = "iso27001"


class TokenScope(Enum):
    """Token scope classifications."""
    READ = "read"
    WRITE = "write"
    EXECUTE = "execute"
    DELEGATE = "delegate"
    ADMIN = "admin"


@dataclass(frozen=True)
class AgentIdentity:
    """
    Persistent cryptographic identity for an agent.
    
    Survives infrastructure changes (domain rotation, cloud migration)
    by deriving identity from behavioral specification rather than
    network location.
    """
    agent_id: str
    public_key: bytes
    system_prompt_hash: str
    tool_list_hash: str
    organization: str
    created_at: float = field(default_factory=time.time)
    metadata: dict[str, Any] = field(default_factory=dict)

    @property
    def fingerprint(self) -> str:
        """Deterministic fingerprint from behavioral spec."""
        combined = f"{self.system_prompt_hash}:{self.tool_list_hash}"
        return hashlib.sha256(combined.encode()).hexdigest()[:16]

    def __str__(self) -> str:
        return f"Agent({self.agent_id[:8]}...@{self.organization})"


@dataclass
class InteractionRecord:
    """
    A single recorded interaction between two agents.
    Used by both ReputationLedger and EastWestMonitor.
    """
    interaction_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    source_agent_id: str = ""
    target_agent_id: str = ""
    task_type: str = ""
    task_description: str = ""
    started_at: float = field(default_factory=time.time)
    completed_at: Optional[float] = None
    success: bool = False
    latency_ms: float = 0.0
    cost_units: float = 0.0
    policy_violations: int = 0
    anomaly_score: float = 0.0
    metadata: dict[str, Any] = field(default_factory=dict)

    @property
    def duration_ms(self) -> float:
        if self.completed_at is None:
            return (time.time() - self.started_at) * 1000
        return (self.completed_at - self.started_at) * 1000


@dataclass
class TrustEdge:
    """
    A directed trust relationship between two agents in the trust graph.
    """
    source_id: str
    target_id: str
    trust_level: TrustLevel
    granted_scopes: list[TokenScope] = field(default_factory=list)
    max_delegation_depth: int = 1
    created_at: float = field(default_factory=time.time)
    expires_at: Optional[float] = None
    consent_chain_id: Optional[str] = None

    @property
    def is_expired(self) -> bool:
        if self.expires_at is None:
            return False
        return time.time() > self.expires_at


@dataclass
class ConsentRecord:
    """
    A single consent hop in a delegation chain.
    Records: who authorized, under what scope, with what expiry, for what task.
    """
    consent_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    chain_id: str = ""
    hop_index: int = 0
    grantor_agent_id: str = ""
    grantee_agent_id: str = ""
    scopes: list[TokenScope] = field(default_factory=list)
    task_type: str = ""
    task_description: str = ""
    granted_at: float = field(default_factory=time.time)
    expires_at: float = 0.0
    signature: str = ""
    parent_consent_id: Optional[str] = None
    metadata: dict[str, Any] = field(default_factory=dict)

    @property
    def is_expired(self) -> bool:
        return time.time() > self.expires_at


@dataclass
class TrustAlert:
    """Alert generated by trust violation detection."""
    alert_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    severity: AlertSeverity = AlertSeverity.WARNING
    alert_type: str = ""
    message: str = ""
    source_agent_id: str = ""
    target_agent_id: Optional[str] = None
    chain: list[str] = field(default_factory=list)
    timestamp: float = field(default_factory=time.time)
    auto_action_taken: Optional[str] = None
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass
class MonitorEvent:
    """A captured east-west traffic event."""
    event_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    source_agent_id: str = ""
    target_agent_id: str = ""
    method: str = ""
    endpoint: str = ""
    request_size_bytes: int = 0
    response_size_bytes: int = 0
    status_code: int = 0
    latency_ms: float = 0.0
    timestamp: float = field(default_factory=time.time)
    anomaly_score: float = 0.0
    tags: list[str] = field(default_factory=list)
    metadata: dict[str, Any] = field(default_factory=dict)
